from enum import Enum
import re

class TokenType(Enum):
    HAI = r"HAI"
    KTHXBYE = r"KTHXBYE"
    WAZZUP = r"WAZZUP"
    BUHBYE = r"BUHBYE"
    BTW = r"BTW"
    OBTW = r"OBTW"
    TLDR = r"TLDR"
    I_HAS_A = r"I HAS A"
    AN = r"AN"
    ITZ = r"ITZ"
    R = r"R"
    SUM_OF = r"SUM OF"
    DIFF_OF = r"DIFF OF"
    PRODUKT_OF = r"PRODUKT OF"
    QUOSHUNT_OF = r"QUOSHUNT OF"
    MOD_OF = r"MOD OF"
    BIGGR_OF = r"BIGGR OF"
    SMALLR_OF = r"SMALLR OF"
    BOTH_OF = r"BOTH OF"
    EITHER_OF = r"EITHER OF"
    WON_OF = r"WON OF"
    NOT = r"NOT"
    ANY_OF = r"ANY OF"
    ALL_OF = r"ALL OF"
    BOTH_SAEM = r"BOTH SAEM"
    DIFFRINT = r"DIFFRINT"
    SMOOSH = r"SMOOSH"
    MAEK = r"MAEK"
    A = r"A"
    IS_NOW_A = r"IS NOW A"
    VISIBLE = r"VISIBLE"
    GIMMEH = r"GIMMEH"
    O_RLY = r"O RLY\?"
    YA_RLY = r"YA RLY"
    MEBBE = r"MEBBE"
    NO_WAI = r"NO WAI"
    OIC = r"OIC"
    WTF = r"WTF\?"
    OMG = r"OMG"
    OMGWTF = r"OMGWTF"
    IM_IN_YR = r"IM IN YR"
    UPPIN = r"UPPIN"
    NERFIN = r"NERFIN"
    YR = r"YR"
    TIL = r"TIL"
    WILE = r"WILE"
    IM_OUTTA_YR = r"IM OUTTA YR"
    HOW_IZ_I = r"HOW IZ I"
    IF_U_SAY_SO = r"IF U SAY SO"
    GTFO = r"GTFO"
    FOUND_YR = r"FOUND YR"
    I_IZ = r"I IZ"
    MKAY = r"MKAY"
    VARIDENT = r'^[a-zA-Z][a-zA-Z0-9\_]*$'
    NUMBR = r"-?(0|[1-9][0-9]*)"
    NUMBAR = r"-?(0|[1-9][0-9]*)\.[0-9]+"
    YARN = r'"\"[^\"]*\""'
    TROOF = r'(WIN|FAIL)'
    TYPE = r'(NOOB|TROOF|NUMBAR|NUMBR|YARN)'
    QUOTES = r'"'
    EOF = r'EOF'
    NEWLINE = r'\n'
    WHITESPACE = r'[ \t]+'
    COMMENT = r'BTW.*'
    STRING_DELIMITER = r'"'
    # UNDEFINED = r'.+'